// <auto-generated />
using System;
using FIRST.Utilities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIRST.Utilities.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241004052329_ReformatModels")]
    partial class ReformatModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FIRST.Utilities.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.ActiveFtcEvent", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.ToTable("ActiveFtcEvents");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.ActiveProgramSeason", b =>
                {
                    b.Property<int>("ActiveProgramSeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonYear")
                        .HasMaxLength(80)
                        .HasColumnType("INTEGER");

                    b.HasKey("ActiveProgramSeasonId");

                    b.HasIndex(new[] { "ProgramCode" }, "Program_Identification")
                        .IsUnique();

                    b.ToTable("ActiveProgramSeasons");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcEvent", b =>
                {
                    b.Property<int>("FtcEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("FtcEventId");

                    b.HasIndex(new[] { "EventCode", "SeasonYear" }, "Event_Identification")
                        .IsUnique();

                    b.ToTable("FtcEvents");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcMatch", b =>
                {
                    b.Property<int>("FtcMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("FtcMatchId");

                    b.HasIndex(new[] { "EventId", "MatchNumber", "TournamentLevel" }, "Match_Identification")
                        .IsUnique();

                    b.ToTable("FtcMatches");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcTeam", b =>
                {
                    b.Property<int>("FtcTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("FtcTeamId");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "TeamNumber", "SeasonYear" }, "Team_Identification")
                        .IsUnique();

                    b.ToTable("FtcTeams");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcTeamMatchJoin", b =>
                {
                    b.Property<int>("MatchesFtcMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamsFtcTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchFtcMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamFtcTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchesFtcMatchId", "TeamsFtcTeamId");

                    b.HasIndex("MatchFtcMatchId");

                    b.HasIndex("TeamFtcTeamId");

                    b.HasIndex("TeamsFtcTeamId");

                    b.ToTable("FtcTeamMatchJoin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.ActiveFtcEvent", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.Models.FtcEvent", "Event")
                        .WithOne("ActiveEvent")
                        .HasForeignKey("FIRST.Utilities.Data.Models.ActiveFtcEvent", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcMatch", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.Models.FtcEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcTeam", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.Models.FtcEvent", "Event")
                        .WithMany("Teams")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcTeamMatchJoin", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.Models.FtcMatch", "Match")
                        .WithMany()
                        .HasForeignKey("MatchFtcMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIRST.Utilities.Data.Models.FtcMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchesFtcMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIRST.Utilities.Data.Models.FtcTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamFtcTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIRST.Utilities.Data.Models.FtcTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsFtcTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIRST.Utilities.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FIRST.Utilities.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIRST.Utilities.Data.Models.FtcEvent", b =>
                {
                    b.Navigation("ActiveEvent");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
